### ISSUE TITLE
The obsidian died when including pdf links

### ISSUE THREAD

**Issue by gh16683170** [tokuhirom/obsidian-advanced-links-lugin#15]
thank you for such a amazing plugin.
i found a bug: when there is a .md file like below:
[[xxx.pdf]]

when enable this plugin, and access this md file, the obsidian will die, it can be 100% reproduce.
ps: if it is ![[xxx.pdf]] is OK, but if it is [[xxx.pdf]] it is NOK.

**Comment by tokuhirom** [comment]
Ah...! I didn't manage PDF files in the obsidian. I forgot it. I'll fix it.

**Comment by tokuhirom** [comment]
Fixed by #17.

**Comment by gh16683170** [comment]
> Fixed by #17.

could you please update the version?

**Comment by tokuhirom** [comment]
Released 0.3.0 and 0.4.0!
