### ISSUE TITLE
seperate the out link the in link

### ISSUE THREAD

**Issue by gh16683170** [tokuhirom/obsidian-advanced-links-lugin#16]
hope can seperate the in & out links. thanks.

**Comment by tokuhirom** [comment]
Do you want to separate it as another row? or in the same row, and it has a different CSS class?

**Comment by gh16683170** [comment]
another row would be nice.&nbsp; because some notes has a lot of out and in links.&nbsp;



---Original---
From: "Tokuhiro ***@***.***&gt;
Date: Mon, May 17, 2021 08:49 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tokuhirom/obsidian-2hop-links-plugin] seperate the out link the in link (#16)




 
Do you want to separate it as another row? or in the same row, and it has a different CSS class?
