### ISSUE TITLE
2hop Links don't always play well with Backlinks Plugin

### ISSUE THREAD

**Issue by brimwats1** [tokuhirom/obsidian-advanced-links-lugin#24]
This is connected to @mrjackphil's https://github.com/mrjackphil/obsidian-backlinks-in-document plugin, which sometimes gets crused by the 2hoplinks:

![image](https://user-images.githubusercontent.com/49103046/118768725-314ef380-b834-11eb-8eb5-ef3e7b06d1cd.png)

**Comment by tokuhirom** [comment]
`obsidian-backlinks-in-document` plugin puts links in `.markdown-preview-view > .workspace-leaf`. It have a `margin-top: -30wh`.
I guess the two-hop links plugin can't fix this issue correctly.  backlinks-in-document plugin can do.

**Comment by mrjackphil** [comment]
@brimwats I'll check the best way to improve the stability of the backlinks-in-document section. 

Current margin applied to the backlinks-in-document section was a necessary evil. But I would like to find another way to place the section where we it should be without using such a hacky and unpleasant way. 

I think what this issue can be closed. I'll create another issue in backlinks-in-document repository with a link to this issue.

**Comment by brimwats1** [comment]
Thanks both of you! I know that backlinks was supposed to be tempoary and will cease operation once obsidian supports it so I appreciate it!
