### ISSUE TITLE
Feature Request : excluded files

### ISSUE THREAD

**Issue by danraymond** [tokuhirom/obsidian-advanced-links-lugin#29]
Would it be possible to have a YAML code in a page which causes that page to be skipped and not have the 2hop links?

**Comment by tokuhirom** [comment]
Reading YFM is a bit heavy operation(It may cause your obsidian app slow).
Is #28 is a good solution for your situation?

**Comment by danraymond** [comment]
Hi Tokuhiro,

Yes it would be.

**Comment by tokuhirom** [comment]
Ok, then I'll merge this issue to #28 and close this issue. Please follow #28 instead.
